# Generated by Django 5.2.5 on 2025-09-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('pseudonimo', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField()),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('departamento', models.CharField(max_length=10, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.biblioteca')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.nacionalidad'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsqk.libro')),
            ],
        ),
    ]
