# Generated by Django 5.2.5 on 2025-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsqk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
